### ISSUE TITLE
Implement todo task CRUD functionality

### ISSUE THREAD

**Issue by kjones7** [kjones7/react-spring-todo#1]
### Frontend
- [ ] Create new tasks
- [ ] Display existing tasks
- [ ] Update existing tasks
- [ ] Delete tasks

### Backend
- [ ] Save new tasks to database
- [ ] Get existing tasks from database
- [ ] Update existing tasks in database
- [ ] Delete existing tasks from database
