### ISSUE TITLE
Make list of tasks UI more useful as a todo list

### ISSUE THREAD

**Issue by kjones7** [kjones7/react-spring-todo#10]
Currently, the todo list is just a bullet list of items. I want to make it so that each task can be quickly checked off, edited, and deleted.

### Tasks
- [ ] Use input to display text and allow it to be edited
- [ ] Use checkboxes to allow tasks to be completed
- [ ] Implement something to allow tasks to be completed quickly (maybe an 'X' after the input, that only displays when the input is in focus?)
